### PR TITLE
Use `%USERPROFILE%` instead of `$HOME` for windows setup

### LINKED ISSUE #58: Installation Issue
```
# v install https://github.com/webui-dev/v-webui

Installing module "webui-dev\v-webui" from "https://github.com/webui-dev/v-webui" to "C:\Users\HD\.vmodules\webui_dev\v_webui" ...
Relocating module from "webui-dev\v-webui" to "vwebui" ( "C:\Users\HD\.vmodules\vwebui" ) ...
Module "webui-dev\v-webui" relocated to "vwebui" successfully.

# v run $HOME/.vmodules/vwebui/setup.vsh

v expects that `$HOME/.vmodules/vwebui/setup.vsh` exists, but it does not
```

I guess, in Windows it should be `%userprofile%` instead of `$HOME`.

```
# v run %userprofile%/.vmodules/vwebui/setup.vsh

Cloning...
git clone --depth 1 https://github.com/webui-dev/webui

Building...
"Build WebUI library (gcc release static)..." 
"Build WebUI library (gcc release dynamic)..." 
"Done."
```

### PR DESCRIPTION
**Pull request by ttytm**
Closes #58

### CODE REVIEW

**Review by hassandraga — APPROVED** [review]

**Comment by hassandraga** [comment]
Just to let you know, you can always directly merge in minor changes. Different reviews and opinions are needed only for major/core changes.

**Comment by ttytm** [comment]
Afaik this repository still requires PRs to be review-approved before I can merge them.

**Comment by ttytm** [comment]
Thanks for the reviews btw. 
I also thought that it would okay to not take up so much of your time with the minor changes, but since permissions changed before I thought it's the way it should be.

**Comment by hassandraga** [comment]
All repos settings are updated now.

**Pull request merged**
