### PR TITLE
Make second window in serve_a_folder example directory independent

### PR DESCRIPTION
**Pull request by ttytm**
the root folder also needs to be set for the second window

### CODE REVIEW

**Review by hassandraga — APPROVED** [review]

**Comment by hassandraga** [comment]
Perhaps we should add `webui_set_root_folder()` for all windows. In V may be `ui.set_root_folder()`.

**Comment by ttytm** [comment]
Yes, sounds awesome!

**Comment by hassandraga** [comment]
Added https://github.com/webui-dev/webui/commit/74830815cd2bf57937f8f6b5fa027d67dccce0de
`ui.set_root_folder()` can refer to `bool webui_set_default_root_folder(const char* path)`.

**Comment by ttytm** [comment]
Nice, thank you!

**Pull request merged**
