### PR TITLE
Update readme header

### PR DESCRIPTION
**Pull request by ttytm**
Updates the readme header: 
https://github.com/ttytm/v-webui/tree/docs/update-readme-header

### CODE REVIEW

**Comment by hassandraga** [comment]
It's good to remove `Original Library License`, but we should leave the V-WebUI License in the bottom of the readme file. Many people don't read the about section in the right side.

**Comment by ttytm** [comment]
Thanks for the review! The license and original library are still in the readme, but they were moved to the very top. The idea was to make both of those even more directly accessible and not to remove them.

> Screenshot from 2023-08-25 17-12-17

Of course, it could be that the new way is not so obvious and that I exhaust the artistic freedom here :D

Let me know / confirm your preference please.

**Comment by hassandraga** [comment]
I like the new `tags` in the top. But I prefer to also keep the `License` in the bottom, and completely remove `Original Library License`. After the merge, I will copy those new tags to all other repos. Thank you for this.

**Comment by ttytm** [comment]
Updated to keep the license :+1:

**Review by hassandraga — APPROVED** [review]

**Pull request merged**
